// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_7-Xmd7vbVMA-mWy0r3lv8kT5XT0Wq0',
    appId: '1:686472546707:android:4c7c8eba7148a4232c8066',
    messagingSenderId: '686472546707',
    projectId: 'zee-chat-c04c3',
    storageBucket: 'zee-chat-c04c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLLIrATCg59DhuZuQRQ79hol19ESgdXM',
    appId: '1:686472546707:ios:64f65d2b9f594bdb2c8066',
    messagingSenderId: '686472546707',
    projectId: 'zee-chat-c04c3',
    storageBucket: 'zee-chat-c04c3.firebasestorage.app',
    androidClientId: '686472546707-rqhc212ikncgtb7k7l4tv0i9ajeops6q.apps.googleusercontent.com',
    iosClientId: '686472546707-utage00tulbjenbc8h4apm5e8hth07hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );

}